---
title: "Shannon Ricci CV"
author: Shannon Ricci
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    css: ['css/styles.css', 'resume']
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(glue)
library(tidyverse)

# Set this to true to have links turned into footnotes at the end of the document
PDF_EXPORT <- FALSE

# Holds all the links that were inserted for placement at the end
links <- c()

source('parsing_functions.R')

# Load csv with position info
position_data <- read_csv('positions.csv')
```


```{r}
# When in export mode the little dots are unaligned, so fix that. 
if(PDF_EXPORT){
  cat("
  <style>
  :root{
    --decorator-outer-offset-left: -6.5px;
  }
  </style>")
}
```


Aside
================================================================================


```{r}
# When in export mode the little dots are unaligned, so fix that. 
# if(PDF_EXPORT){
#   cat("View this CV online with links at _nickstrayer.me/cv_")
# } else {
#   cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://github.com/nstrayer/cv/raw/master/strayer_cv.pdf)")
# }
```

Contact {#contact}
--------------------------------------------------------------------------------


- <i class="fa fa-envelope"></i> swbrown@ncsu.edu
- <i class="fa fa-twitter"></i> swricci
- <i class="fa fa-github"></i> github.com/swricci
- <i class="fa fa-phone"></i> (845) 803-2019



Skills {#skills}
--------------------------------------------------------------------------------

```{r}
skills <- tribble(
  ~skill,               ~level,
  "MATLAB",                  5,
  "R", 4,
  "ArcGIS Pro",             4,
  "QGIS", 3,
)

build_skill_bars(skills)
```





Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with the R package [**pagedown**](https://github.com/rstudio/pagedown). 

The source code is available at [github.com/nstrayer/cv](https://github.com/nstrayer/cv).

Last updated on `r Sys.Date()`.




Main
================================================================================
Shannon Ricci {#title}
--------------------------------------------------------------------------------


```{r}
intro_text <- "Interests: data analysis, data visualization, marine benthic biology and ecology, conservation, invertebrate fisheries, passive acoustics, informal environmental science education 

"

cat(sanitize_links(intro_text))
```



Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, 'education')
```



Research Experience {data-icon=laptop}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, 'research_positions')
```



Teaching & Outreach Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, 'teaching_positions')
```


Publications {data-icon=book}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, 'academic_articles')
```

Selected Presentations {data-icon=chart-line}
--------------------------------------------------------------------------------

```{r}
print_section_nodesc(position_data, 'presentations')
```


Community Engagement {data-icon=handshake}
--------------------------------------------------------------------------------

```{r}
print_section_nodesc(position_data, 'community_engagement')
```

Selected Press (By)  {data-icon=newspaper}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, 'by_me_press')
```


```{r}
if(PDF_EXPORT){
  cat("
  
Links {data-icon=link}
--------------------------------------------------------------------------------

<br>


")
  
  walk2(links, 1:length(links), function(link, index){
    print(glue('{index}. {link}'))
  })
}
```


