---
title: Shannon Ricci's Resume
author: Shannon Ricci
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    css: ['css/custom_resume.css', 'css/styles.css', 'resume']
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: true

---


```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)
library(tidyverse)
library(glue)

# Set this to true to have links turned into footnotes at the end of the document
PDF_EXPORT <- FALSE

# Holds all the links that were inserted for placement at the end
links <- c()

source('parsing_functions.R')


# First let's get the data, filtering to only the items tagged as
# Resume items
position_data <- read_csv('positions.csv') %>% 
  filter(in_resume) 
# %>% 
#   #mutate(
#     # Build some custom sections by collapsing others
#     section = case_when(
#       section %in% c('research_positions', 'industry_positions') ~ 'positions', 
#       section %in% c('data_science_writings', 'by_me_press') ~ 'writings',
#       TRUE ~ section
#     )
#   ) 

```


Aside
================================================================================



Contact {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> swbrown@ncsu.edu
- <i class="fa fa-twitter"></i> @swricci
- <i class="fa fa-github"></i> [github.com/swricci](https://github.com/swricci)
- <i class="fa fa-phone"></i> (845) 803-2019



Skills {#skills}
--------------------------------------------------------------------------------


```{r}
library(tidyverse)
library(glue)
source('parsing_functions.R')

skills <- tribble(
  ~skill,               ~level,
  "MATLAB",                  5,
  "R", 4,
  "Python", 2,
  "ArcGIS Pro",             4,
  "QGIS", 3,
)

build_skill_bars(skills)
```


More info {#more-info}
--------------------------------------------------------------------------------

To view my full CV and a more complete list of positions and publications, go to:
[swricci.github.io/cv](swricci.github.io/cv)

Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made w/ [**pagedown**](https://github.com/rstudio/pagedown). 

Source code: [github.com/nstrayer/cv](https://github.com/nstrayer/cv).

Last updated on `r Sys.Date()`.




Main
================================================================================

Shannon Ricci {#title}
--------------------------------------------------------------------------------

```{r}
intro_text <- "Interests: data analysis, data visualization, marine benthic ecology, conservation, passive acoustics, informal environmental science education 

"

cat(sanitize_links(intro_text))
```



Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
position_data %>% print_section('education')
```



Research Experience {data-icon=laptop}
--------------------------------------------------------------------------------

```{r}
position_data %>% print_section('research_positions')
```



Selected Publications {data-icon=book}
--------------------------------------------------------------------------------

```{r}
position_data %>% print_section('academic_articles')
```



Selected Presentations {data-icon=chart-line}
--------------------------------------------------------------------------------

```{r}
print_section_nodesc(position_data, 'presentations')
```


Teaching & Outreach Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------
:::aside
Research-related press:

[Remote Sensing and the Science of Sound](https://cnr.ncsu.edu/geospatial/news/2020/01/30/remote-sensing-and-the-science-of-sound/)

[Music in the Marsh: The Summer Soundscapes of the Rachel Carson Reserve](https://ncseagrant.ncsu.edu/coastwatch/previous-issues/2015-2/summer-2015/music-in-the-marsh-the-summer-soundscapes-of-the-rachel-carson-reserve/)
:::

```{r}
position_data %>% print_section('teaching_positions')
```
